# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Purpouse CI/CD"
  lane :distribute do
      #build_android_app(task: ":app:assembleDebug")
      sh("cd ../.. && flutter clean")
      sh("cd ../.. && flutter pub get")
      sh("cd ../.. && flutter build apk --release")
      APK_PATH = "../build/app/outputs/apk/release/app-release.apk"
      release = firebase_app_distribution(
          app: "1:182601458343:android:purpouse-da298",
          testers: "andrea.riezzo@kalpa.it",
          release_notes: "Lots of amazing new features to test out!",
          apk_path: APK_PATH
      )
  end

end
