name: Flutter CI/CD Development Release

on:
  push:
    branches:
      - develop

jobs:
  firebase_android_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Commit Message for Release Trigger
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -q "release (develop): version"; then
            echo "::notice file=trigger.log,line=1::Commit message contains release trigger. Starting deployment."
          else
            echo "::notice file=trigger.log,line=1::Commit message does NOT contain release trigger. Skipping deployment."
            exit 0 # Esci dal job con successo (ignorando i passaggi successivi)
          fi

      - name: Setup Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.7'
          bundler-cache: true
          cache-version: 1

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 3.22.6'
          channel: 'stable'

      - name: Setup Android Keystore for Signing
        run: |
          cd android
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.jks
          echo "storeFile=app/release.jks" > key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties 

      - name: Setup Firebase SA Key
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service_account_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/service_account_key.json" >> $GITHUB_ENV

      - name: Run Fastlane Android Distribute to Firebase
        run: |
          cd android
          VERSION=$(grep 'version:' ../pubspec.yaml | cut -d+ -f1 | cut -d: -f2 | tr -d ' ')
          bundle exec fastlane distribute app_id: "${{ secrets.FIREBASE_ANDROID_APP_ID }}" version: $VERSION